# Generated by Django 2.2.6 on 2019-10-30 02:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=64)),
                ('client_tag', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=64)),
                ('route', models.CharField(max_length=64)),
                ('hierarchy_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('seconds', models.IntegerField()),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.Client')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('analysis', models.TextField()),
            ],
            options={
                'db_table': 'timeseries',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpid', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=64)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(blank=True, max_length=11)),
                ('user_type', models.CharField(max_length=11)),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_confirmed', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.Client')),
                ('creator_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apirest.User')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=64)),
                ('route', models.CharField(max_length=64)),
                ('clients', models.ManyToManyField(blank=True, to='apirest.Client', verbose_name='Client')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.Group')),
                ('roles', models.ManyToManyField(blank=True, to='apirest.Role', verbose_name='Role')),
            ],
        ),
    ]
